

FIND_PATH(HDF5_INCLUDE_DIRS NAMES hdf5.h PATHS_SUFFIXES hdf5)
MESSAGE(STATUS "Found HDF5 include: ${HDF5_INCLUDE_DIRS}")
include_directories(${HDF5_INCLUDE_DIRS})

FIND_PATH(HDF5_HL_INCLUDE_DIRS NAMES hdf5_hl.h PATHS_SUFFIXES hdf5_hl)
MESSAGE(STATUS "Found HDF5_HL include: ${HDF5_HL_INCLUDE_DIRS}")
include_directories(${HDF5_HL_INCLUDE_DIRS})


FIND_LIBRARY(HDF5_hdf5_LIBRARY NAMES "libhdf5.lib"  PATHS_SUFFIXES hdf5)
FIND_LIBRARY(HDF5_LIBRARIES NAMES "libhdf5.lib"  PATHS_SUFFIXES hdf5)
FIND_LIBRARY(HDF5_HL_LIBRARIES NAMES "libhdf5_hl.lib"  PATHS_SUFFIXES hdf5_hl)


MARK_AS_ADVANCED(
    HDF5_INCLUDE_DIRS
    HDF5_HL_INCLUDE_DIRS
    HDF5_hdf5_LIBRARY
    HDF5_LIBRARIES
    HDF5_HL_LIBRARIES
)
