name: windows-2019

on:
  push:
    branches: [ windows-2019 ]
  pull_request:
    branches: [ windows-2019 ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # pin to windows-2019
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    
    - name: pip3
      run: pip3 install Cython>=0.19.2 numpy scipy scikit-image matplotlib>=1.3.1 ipython>=3.0.0 h5py>=2.2.0 networkx==2.2 nose>=1.3.0 pandas python-dateutil>=2.6.0 protobuf>=2.5.0 python-gflags>=2.0 pyyaml>=3.10 Pillow>=2.3.0 six>=1.1.0 pydotplus graphviz pydot 
      shell: cmd
    
    - name: vcpkg
      run: set PATH=%VCPKG_INSTALLATION_ROOT%;%PATH%
      shell: cmd
      
    - name: vcpkg integrate install
      run: vcpkg integrate install
      
    - name: vcpkg install
      run: vcpkg install lmdb gflags glog leveldb snappy protobuf matio hdf5[cpp,tools,utils] h5py-lzf opencv3[contrib,nonfree,world] openblas zlib libjpeg-turbo python3 boost boost-system boost-thread boost-filesystem boost-regex boost-smart-ptr boost-function boost-date-time boost-bind boost-random boost-math boost-algorithm boost-python[python3] --triplet x64-windows-static
      # run: vcpkg install openblas zlib  --triplet x64-windows


    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_GENERATOR="Visual Studio 16 2019" -DARCHITECTURE=x64  -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake  -DVCPKG_TARGET_TRIPLET=x64-windows-static  -DBoost_USE_STATIC_LIBS=ON -DBOOST_ROOT="C:/vcpkg/installed/x64-windows-static" -DBOOST-PYTHON_ROOT="C:/vcpkg/installed/x64-windows-static" -DBOOST_LIBRARYDIR="C:/vcpkg/installed/x64-windows-static" -DZLIB_ROOT="C:/vcpkg/installed/x64-windows-static" -DUSE_LMDB=1 -DUSE_HDF5=1 -DUSE_LEVELDB=1 -DUSE_MATIO=1

    - name: Build it
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -DCMAKE_GENERATOR="Visual Studio 16 2019" -DARCHITECTURE=x64  -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake  -DVCPKG_TARGET_TRIPLET=x64-windows-static -DBoost_USE_STATIC_LIBS=ON -DUSE_LMDB=1  -DUSE_HDF5=1 -DUSE_LEVELDB=1 -DUSE_MATIO=1 

    - name: Target runtest
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target runtest -DCMAKE_GENERATOR="Visual Studio 16 2019" -DARCHITECTURE=x64  -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake  -DVCPKG_TARGET_TRIPLET=x64-windows-static -DBoost_USE_STATIC_LIBS=ON -DUSE_LMDB=1  -DUSE_HDF5=1 -DUSE_LEVELDB=1 -DUSE_MATIO=1 
