name: windows-2019

on:
  push:
    branches: [ windows-2019 ]
  pull_request:
    branches: [ windows-2019 ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # pin to windows-2019
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    
    - name: pip3
      run: pip3 install Cython>=0.19.2 numpy scipy scikit-image matplotlib>=1.3.1 ipython>=3.0.0 h5py>=2.2.0 networkx==2.2 nose>=1.3.0 pandas python-dateutil>=2.6.0 protobuf>=2.5.0 python-gflags>=2.0 pyyaml>=3.10 Pillow>=2.3.0 six>=1.1.0 pydotplus graphviz pydot 
      shell: cmd
    
    - name: vcpkg
      run: set PATH=%VCPKG_INSTALLATION_ROOT%;%PATH%
      shell: cmd
      
    - name: vcpkg integrate install
      run: vcpkg integrate install
      
    - name: vcpkg install
      run: vcpkg install opencv2 --triplet x64-windows-static-md
      
    - name: vcpkg install
      run: vcpkg install lmdb gflags glog leveldb snappy protobuf matio hdf5 openblas zlib libjpeg-turbo boost boost-system boost-thread boost-filesystem boost-regex boost-smart-ptr boost-function boost-date-time boost-bind boost-random boost-math boost-algorithm boost-python[python3] --triplet x64-windows-static-md
      shell: cmd

    - name: print dir
      run: cd /d c:\ && cd C:/vcpkg/installed/x64-windows-static-md/lib && dir
      shell: cmd


    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Visual Studio 16 2019" -A x64  -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake  -DVCPKG_TARGET_TRIPLET=x64-windows-static-md  -DCMAKE_C_FLAGS=-IC:/vcpkg/installed/x64-windows-static-md/include   -DCMAKE_CXX_FLAGS=-IC:/vcpkg/installed/x64-windows-static-md/include -DHDF5_hdf5_LIBRARY="C:/vcpkg/installed/x64-windows-static-md/lib"  -DBoost_USE_STATIC_LIBS=OFF -DBOOST_NO_EXCEPTIONS=0  -DBOOST_ROOT="C:/vcpkg/installed/x64-windows-static-md" -DBOOST_INCLUDEDIR="C:/vcpkg/installed/x64-windows-static-md/include/boost"  -DBOOST_LIBRARYDIR="C:/vcpkg/installed/x64-windows-static-md/lib" -DZLIB_ROOT="C:/vcpkg/installed/x64-windows-static-md" -DCPU_ONLY=1  -DUSE_LMDB=1 -DUSE_HDF5=1 -DUSE_LEVELDB=1 -DUSE_MATIO=1 -DBUILD_python=0

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}  

    - name: Target runtest
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target runtest  

    
